# Generated by Django 3.2.20 on 2023-12-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_roomcategory_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
